version: '3.3'

services:
  cache:
    image: redis:7
    networks:
      - dnet
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  data:
  cache:
    driver: local


networks:
  dnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24