version: '3.3'

services:
  api:
    build: .
    container_name: api
    entrypoint: uvicorn
    command: api.api:app --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    networks:
      - dnet

  redis:
    image: redis:7
    networks:
      - dnet
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - data:/data

  celery-worker:
      build: .
      container_name: celery-worker
      entrypoint: celery
      command: -A celery_app.app worker -l info
      volumes:
      - .:/celery/worker
      links:
      - redis
      depends_on:
      - redis
      networks:
      - dnet

  celery-beat:
      build: .
      container_name: celery-beat
      entrypoint: celery
      command: -A celery_app.app beat -l info
      volumes:
      - .:/celery/beat
      links:
      - celery-worker
      - redis
      depends_on:
      - celery-worker
      - redis
      networks:
      - dnet

volumes:
  data:
    driver: local


networks:
  dnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24